import { useEffect, useState } from "react";
import UploadForm from "./components/UploadForm.jsx";
import ResultCard from "./components/ResultCard.jsx";
import { analyzeImage } from "./api.js";
import { USE_MOCK } from "./config.js";

/**
 * Top-level component. Owns the application state machine:
 *   idle -> (file selected) -> ready -> (analyze) -> loading -> result | error
 */
export default function App() {
  const [file, setFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [status, setStatus] = useState("idle"); // idle | loading | done
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  // Build (and clean up) an object URL for the image preview.
  useEffect(() => {
    if (!file) {
      setPreviewUrl(null);
      return;
    }
    const url = URL.createObjectURL(file);
    setPreviewUrl(url);
    // Revoke the URL when the file changes or the component unmounts.
    return () => URL.revokeObjectURL(url);
  }, [file]);

  function handleFileSelected(selected) {
    setFile(selected);
    setResult(null);
    setError(null);
    setStatus("idle");
  }

  function handleValidationError(message) {
    setFile(null);
    setResult(null);
    setStatus("idle");
    setError(message);
  }

  // Reset everything back to the initial state.
  function handleReset() {
    setFile(null);
    setResult(null);
    setError(null);
    setStatus("idle");
  }

  // Send the image to the backend (or mock) and handle the response/errors.
  async function handleAnalyze() {
    if (!file) return;
    setStatus("loading");
    setError(null);
    setResult(null);
    try {
      const data = await analyzeImage(file);
      setResult(data);
      setStatus("done");
    } catch (err) {
      setError(
        err.message || "Something went wrong while analyzing the image."
      );
      setStatus("idle");
    }
  }

  const isLoading = status === "loading";

  return (
    <div className="page">
      <main className="card">
        <header className="card__head">
          <h1 className="card__title">AI Image Detector</h1>
          <p className="card__subtitle">
            Upload an image to check whether it was generated by AI.
          </p>
          {USE_MOCK && (
            <span className="card__mock-badge" title="Backend not connected">
              Demo mode (mock backend)
            </span>
          )}
        </header>

        {/* Show the dropzone until an image is selected. */}
        {!file && (
          <UploadForm
            onFileSelected={handleFileSelected}
            onValidationError={handleValidationError}
            disabled={isLoading}
          />
        )}

        {/* Preview + actions once an image is selected. */}
        {file && (
          <div className="preview">
            <img
              className="preview__img"
              src={previewUrl}
              alt="Selected upload preview"
            />
            <p className="preview__name" title={file.name}>
              {file.name}
            </p>

            <div className="actions">
              <button
                className="btn btn--primary"
                onClick={handleAnalyze}
                disabled={isLoading}
              >
                {isLoading ? "Analyzing…" : "Analyze image"}
              </button>
              <button
                className="btn btn--ghost"
                onClick={handleReset}
                disabled={isLoading}
              >
                Choose another
              </button>
            </div>
          </div>
        )}

        {/* Error banner (validation or network). */}
        {error && (
          <div className="alert" role="alert">
            {error}
          </div>
        )}

        {/* Result card. */}
        {result && status === "done" && <ResultCard result={result} />}
      </main>

      <footer className="footer">
        <p>Thesis project · AI-generated image detection</p>
      </footer>
    </div>
  );
}
